version: '3.1'
services:
  db:
    image: mysql:8.0.27
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"   
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro      
